version: 2

project_name: phpunit-parallel

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

homebrew_casks:
  - repository:
      owner: alexdempster44
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    directory: Casks
    homepage: "https://github.com/alexdempster44/phpunit-parallel"
    description: "A CLI tool to run PHPUnit tests in parallel, with a beautiful terminal UI"
    license: "MIT"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
